# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool: Default
name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
- group: JFrog
- name: solution 
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/Kozachok.WebAPI.csproj'
  displayName: 'Restore Nuget Packages'

- task: DotNetCoreCLI@2
  inputs: 
    command: 'build'
    projects: '**/Kozachok.WebAPI.csproj'
    arguments: '--no-restore' 
  displayName: 'Build projects'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'test'
#    projects: '**/*Test.csproj'
#    arguments: '--no-restore --no-build'
#  displayName: 'Run Tests'

- task: CmdLine@2
  inputs:
    script: 'systemctl stop kozachokdev.service'
  displayName: 'Stop kozachokdev.service WebAPI'

- task: CopyFiles@2
  inputs:
    SourceFolder: '/var/www/kozachokApi'
    Contents: '**'
    OverWrite: true
    TargetFolder: '/var/www/backup_kozachokApi'
  displayName: 'make a backup'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Kozachok.WebAPI.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
    modifyOutputPath: false
  displayName: 'Publish VideoTranslate'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/publish.zip'
    destinationFolder: '/var/www/kozachokApi'
    cleanDestinationFolder: true
    overwriteExistingFiles: true
  displayName: 'Copy published files into Production folder'

- task: CmdLine@2
  inputs:
    script: 'systemctl start kozachokdev.service'
  displayName: 'Start kozachokdev.service WebAPI'