CREATE TABLE [dbo].[T_Stored_Event](
	[Id] [UNIQUEIDENTIFIER] CONSTRAINT DF_T_Shared_Event_Id DEFAULT NEWID() NOT NULL,
	[AggregateId] [UNIQUEIDENTIFIER] NOT NULL,
	[MessageType] [VARCHAR](500) NOT NULL,
	[Data] [NVARCHAR](MAX) NOT NULL,
	[User] [VARCHAR](500) NOT NULL,
	[CreatedDateUTC] [DATETIME] CONSTRAINT DF_T_Shared_Event_CreatedDateUTC DEFAULT GETUTCDATE() NOT NULL,
	CONSTRAINT [T_Shared_Event_Id] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
)
GO

CREATE TABLE [dbo].[T_User](
	[Id] [UNIQUEIDENTIFIER] CONSTRAINT DF_T_User_Id DEFAULT NEWID() NOT NULL,
	[Name] [VARCHAR](200) NOT NULL,
	[Email] [VARCHAR](200) NOT NULL,
	[Password] [VARCHAR](500) NOT NULL,
	[CreatedDateUTC] [DATETIME] CONSTRAINT DF_T_User_CreatedDateUTC DEFAULT GETUTCDATE() NOT NULL,
	CONSTRAINT [T_User_Id] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
)
GO
