CREATE TABLE [dbo].[L_Room_Type](
	[Id] TINYINT NOT NULL,
	[Value] NVARCHAR(200) NOT NULL,
	CONSTRAINT [L_Room_Type_Id] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
)
GO

INSERT INTO [dbo].[L_Room_Type]([Id], [Value])
VALUES(0, 'Public'),
	(1, 'Private')
GO

CREATE TABLE [dbo].[T_Room](
	[Id] [UNIQUEIDENTIFIER] CONSTRAINT DF_T_Room_Id DEFAULT NEWID() NOT NULL,
	[Name] [VARCHAR](500) NOT NULL,
	[RoomTypeId] [TINYINT] NOT NULL CONSTRAINT FK_T_Room_RoomTypeId_To_L_Room_Type_Id FOREIGN KEY REFERENCES [dbo].[L_Room_Type](Id),
	[OwnerUserId] [UNIQUEIDENTIFIER] NOT NULL CONSTRAINT FK_T_Room_OwnerUserId_To_T_User_Id FOREIGN KEY REFERENCES [dbo].[T_User](Id),
	[CreatedDateUTC] [DATETIME] CONSTRAINT DF_T_Room_CreatedDateUTC DEFAULT GETUTCDATE() NOT NULL,
	CONSTRAINT [T_Room_Id] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
)
GO

CREATE TABLE [dbo].[T_Room_User](
	[Id] [UNIQUEIDENTIFIER] CONSTRAINT DF_T_Room_User_Id DEFAULT NEWID() NOT NULL,
	[RoomId] [UNIQUEIDENTIFIER] NOT NULL CONSTRAINT FK_T_Room_User_RoomId_To_T_Room_Id FOREIGN KEY REFERENCES [dbo].[T_Room](Id),
	[UserId] [UNIQUEIDENTIFIER] NOT NULL CONSTRAINT FK_T_Room_User_UserId_To_T_User_Id FOREIGN KEY REFERENCES [dbo].[T_User](Id),
	[IsOwner] BIT NOT NULL CONSTRAINT DF_T_Room_User_IsOwner DEFAULT(0),
	[CreatedDateUTC] [DATETIME] CONSTRAINT DF_T_Room_User_CreatedDateUTC DEFAULT GETUTCDATE() NOT NULL,
	CONSTRAINT [T_Room_User_Id] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
)
GO
